version: "3.7"

services:
  my-database:
    image: postgres:latest
    # container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: "UserName"
      POSTGRES_PASSWORD: "Password"
    ports:
      - 5432:5432
  my-backend:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ./src:/myfolder/src

    ports:
      - 3000:3000
    
    # depends_on:
    # - my-database
    
    # command: ["/myfolder/start.sh"]
